media:
  input: images
  output: /images
  path: images
  categories:
    - image
settings:
  hide: true
  content:
    merge: true
content:
  - name: pages
    label: Pages
    path: pages
    type: collection
    subfolders: false
    view:
      fields:
        - meta_title
      primary: meta_title
      sort:
        - meta_title
    fields:
      - { name: subtitle, type: string, label: Subtitle }
      - name: body
        label: Body
        type: code
        options:
          language: markdown
      - { name: meta_title, type: string, label: Meta Title, maxlength: 55 }
      - name: meta_description
        type: string
        label: Meta Description
        maxlength: 155
      - name: eleventyNavigation
        label: Navigation
        type: object
        fields:
          - { name: key, type: string }
          - { name: order, type: number }
      - { name: layout, type: string }
      - name: faqs
        label: FAQs
        type: object
        list: true
        fields:
          - { name: question, type: string, label: Question, required: true }
          - { name: answer, type: string, label: Answer, required: true }
  - name: categories
    label: Categories
    path: categories
    type: collection
    subfolders: false
    filename: "{primary}.md"
    fields:
      - { name: title, type: string, label: Title }
      - { name: thumbnail, type: image, label: Thumbnail }
      - name: body
        label: Body
        type: code
        options:
          language: markdown
      - { name: featured, type: boolean, label: Featured }
      - { name: meta_title, type: string, label: Meta Title, maxlength: 55 }
      - name: meta_description
        type: string
        label: Meta Description
        maxlength: 155
      - { name: subtitle, type: string, label: Subtitle }
      - name: faqs
        label: FAQs
        type: object
        list: true
        fields:
          - { name: question, type: string, label: Question, required: true }
          - { name: answer, type: string, label: Answer, required: true }
  - name: reviews
    label: Reviews
    path: reviews
    type: collection
    subfolders: false
    fields:
      - { name: name, type: string, label: Name }
      - { name: url, type: string, label: URL }
      - { name: rating, type: number, label: Rating }
      - { name: thumbnail, type: image, label: Reviewer Photo }
      - name: body
        label: Body
        type: code
        options:
          language: markdown
      - name: faqs
        label: FAQs
        type: object
        list: true
        fields:
          - { name: question, type: string, label: Question, required: true }
          - { name: answer, type: string, label: Answer, required: true }
  - name: homepage
    label: Homepage Settings
    type: file
    path: _data/homepage.json
    fields:
      - name: show_products
        type: boolean
        label: Show Products Section
        default: true
      - name: show_menus
        type: boolean
        label: Show Menus Section
        default: true
      - name: show_news
        type: boolean
        label: Show News Section
        default: true
      - name: show_recurring_events
        type: boolean
        label: Show Recurring Events
        default: true
  - name: site
    label: Site Configuration
    type: file
    path: _data/site.json
    fields:
      - { name: name, type: string, label: Site Name }
      - { name: url, type: string, label: Site URL }
      - name: opening_times
        label: Opening Times
        type: object
        list: true
        fields:
          - { name: day, type: string, label: Day, required: true }
          - { name: hours, type: string, label: Hours, required: true }
      - name: socials
        label: Social Media Links
        type: object
        fields:
          - { name: Github, type: string, label: Github }
          - { name: Forgejo, type: string, label: Forgejo }
          - { name: Facebook, type: string, label: Facebook }
          - { name: Instagram, type: string, label: Instagram }
          - { name: TikTok, type: string, label: TikTok }
          - { name: Google, type: string, label: Google }
          - { name: WhatsApp, type: string, label: WhatsApp }
          - { name: RSS, type: string, label: RSS }
      - { name: map_embed_src, type: string, label: Map Embed URL }
  - name: meta
    label: Meta Configuration
    type: file
    path: _data/meta.json
    fields:
      - { name: language, type: string, label: Language Code, default: en-GB }
      - name: organization
        label: Organization
        type: object
        fields:
          - { name: description, type: string, label: Organization Description }
          - { name: legalName, type: string, label: Legal Name }
          - { name: foundingDate, type: string, label: Founding Date }
          - name: founders
            label: Founders
            type: object
            list: true
            fields:
              - { name: name, type: string, label: Name }
          - name: address
            label: Address
            type: object
            fields:
              - { name: streetAddress, type: string, label: Street Address }
              - { name: addressLocality, type: string, label: City }
              - { name: addressRegion, type: string, label: Region/State }
              - { name: postalCode, type: string, label: Postal Code }
              - { name: addressCountry, type: string, label: Country Code }
          - name: contactPoint
            label: Contact Points
            type: object
            list: true
            fields:
              - { name: telephone, type: string, label: Telephone }
              - { name: contactType, type: string, label: Contact Type }
              - { name: areaServed, type: string, label: Area Served }
              - name: availableLanguage
                type: string
                label: Available Languages
                list: true
  - name: alt-tags
    label: Image Alt Tags
    type: file
    path: _data/alt-tags.json
    fields:
      - name: images
        type: object
        list: true
        fields:
          - { name: path, type: image, label: Image }
          - { name: alt, type: string, label: Alt Text }